title: Coach Big Mack's Physics
description: Learning Physics with One Coach Big Mack
baseurl: ""
url: "https://vangrou.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
kramdown:
  math_engine: mathjax
highlighter: rouge
